language: rust
rust:
    - nightly
sudo: false
dist: trusty
os: linux
cache:
    directories:
        - $HOME/.cargo
        - target
before_script:
    - curl -L https://github.com/arcnmx/ci/archive/master.tar.gz | tar -xzC $HOME && . $HOME/ci-master/src

script:
    - cargo test
    - cargo build

deploy:
    provider: script
    script: "true"
    on:
        tags: true
        all_branches: true
        condition: "$TRAVIS_RUST_VERSION = nightly"

before_deploy:
    - cargo doc
    - cargo package

after_deploy:
    - cargo pages-publish
    - cargo publish
